# coding: utf-8

"""
Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

GrabFood

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.1.3

 Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
"""


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CancelCode(int, Enum):
    """
    The cancel code for a specific cancel reason.
    """

    """
    allowed enum values
    """
    NUMBER_1001 = 1001
    NUMBER_1002 = 1002
    NUMBER_1003 = 1003
    NUMBER_1004 = 1004

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CancelCode from a JSON string"""
        return cls(json.loads(json_str))


