# coding: utf-8

"""
Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

GrabFood

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.1.3

 Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
"""


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CancelOrderLimitType(str, Enum):
    """
    The type of the order cancellation limit.
    """

    """
    allowed enum values
    """
    NOT_APPROACHING_LIMIT = 'not approaching limit'
    APPROACHING_THE_DAILY_LIMIT = 'approaching the daily limit'
    APPROACHING_THE_WEEKLY_LIMIT = 'approaching the weekly limit'
    APPROACHING_THE_MONTHLY_LIMIT = 'approaching the monthly limit'
    EMPTY = ''

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CancelOrderLimitType from a JSON string"""
        return cls(json.loads(json_str))


