# coding: utf-8

"""
Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

GrabFood

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.1.3

 Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class OrderPromo(BaseModel):
    """
    OrderPromo
    """ # noqa: E501
    code: Optional[StrictStr] = Field(default=None, description="Promo code applied in the order.")
    description: Optional[StrictStr] = Field(default=None, description="Promo description.")
    name: Optional[StrictStr] = Field(default=None, description="Name of the promotion.")
    promo_amount: Optional[StrictInt] = Field(default=None, description="Promo amount applied in the order, in local currency. This amount is rounded into whole number.", alias="promoAmount")
    mex_funded_ratio: Optional[StrictInt] = Field(default=None, description="The merchant's funded ratio of the promo in percentage.", alias="mexFundedRatio")
    mex_funded_amount: Optional[StrictInt] = Field(default=None, description="The merchant's promo fund in the minor unit. Calculated based on merchant funded ratio.", alias="mexFundedAmount")
    targeted_price: Optional[StrictInt] = Field(default=None, description="The subtotal of the order basket in minor unit.", alias="targetedPrice")
    promo_amount_in_min: Optional[StrictInt] = Field(default=None, description="Promo amount applied in the order in minor unit.", alias="promoAmountInMin")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["code", "description", "name", "promoAmount", "mexFundedRatio", "mexFundedAmount", "targetedPrice", "promoAmountInMin"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OrderPromo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OrderPromo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "code": obj.get("code"),
            "description": obj.get("description"),
            "name": obj.get("name"),
            "promoAmount": obj.get("promoAmount"),
            "mexFundedRatio": obj.get("mexFundedRatio"),
            "mexFundedAmount": obj.get("mexFundedAmount"),
            "targetedPrice": obj.get("targetedPrice"),
            "promoAmountInMin": obj.get("promoAmountInMin")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


