# coding: utf-8

"""
Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

GrabFood

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.1.3

 Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class OutOfStockInstruction(BaseModel):
    """
    An JSON object that indicates the instructions to be taken by the merchant when the item is out of stock.
    """ # noqa: E501
    title: Optional[StrictStr] = Field(default=None, description="The short instruction message.")
    instruction_type: Optional[StrictStr] = Field(default=None, description="Type of out-of-stock instruction chosen by customer. `CONTACT` is disabled by default, kindly reach out to your integration manager if you wish to receive this instruction.", alias="instructionType")
    replacement_item_id: Optional[StrictStr] = Field(default=None, description="The preferred item's ID in the partner system. Only applicable when the instructionType is `SPECIFIC_ITEM`.", alias="replacementItemID")
    replacement_grab_item_id: Optional[StrictStr] = Field(default=None, description="The preferred item's ID in the Grab system. Only applicable when the instructionType is `SPECIFIC_ITEM`.", alias="replacementGrabItemID")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["title", "instructionType", "replacementItemID", "replacementGrabItemID"]

    @field_validator('instruction_type')
    def instruction_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['REMOVE', 'CANCEL', 'SPECIFIC_ITEM', 'CONTACT']):
            raise ValueError("must be one of enum values ('REMOVE', 'CANCEL', 'SPECIFIC_ITEM', 'CONTACT')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OutOfStockInstruction from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OutOfStockInstruction from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "title": obj.get("title"),
            "instructionType": obj.get("instructionType"),
            "replacementItemID": obj.get("replacementItemID"),
            "replacementGrabItemID": obj.get("replacementGrabItemID")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


