# coding: utf-8

"""
Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

GrabFood

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.1.3

 Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from grabfood.models.pos_item_modifier import PosItemModifier
from typing import Optional, Set
from typing_extensions import Self

class POSItem(BaseModel):
    """
    POSItem
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="The item's externalID in the partner system. ")
    grab_item_id: Optional[StrictStr] = Field(default=None, description="The item's ID in Grab system. Partner can use this field in the `EditOrder` endpoint. Note: The index number (after `#`) is different for the same item with different modifiers. This helps identify items when editing complex orders. This is currently controlled by feature flag until full rollout, for non whitelisted partners, the '#' and index number will not be included. ", alias="grabItemID")
    name: Optional[StrictStr] = Field(default=None, description="The name of the item.")
    quantity: Optional[StrictInt] = Field(default=None, description="The number of the item ordered.")
    modifiers: Optional[List[PosItemModifier]] = Field(default=None, description="The ordered items in an array of JSON Object. ")
    price: Optional[StrictInt] = Field(default=None, description="The price for a single item along with its associated modifiers in minor unit and tax-inclusive.  ``` price = Item price(tax inclusive) + Modifier price(tax inclusive) | (2241*1.06)+(165*1.06)=2550 ")
    tax: Optional[StrictInt] = Field(default=None, description="Tax in minor format for a single item along with its associated modifiers. `0` if tax configuration is absent. Refer to FAQs for more details about [tax](#section/Order/How-is-tax-calculated). ``` tax = Item tax + Modifier tax | (2241*0.06)+(165*0.06)=144 ")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "grabItemID", "name", "quantity", "modifiers", "price", "tax"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of POSItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in modifiers (list)
        _items = []
        if self.modifiers:
            for _item_modifiers in self.modifiers:
                if _item_modifiers:
                    _items.append(_item_modifiers.to_dict())
            _dict['modifiers'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of POSItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "grabItemID": obj.get("grabItemID"),
            "name": obj.get("name"),
            "quantity": obj.get("quantity"),
            "modifiers": [PosItemModifier.from_dict(_item) for _item in obj["modifiers"]] if obj.get("modifiers") is not None else None,
            "price": obj.get("price"),
            "tax": obj.get("tax")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


