# coding: utf-8

"""
Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

GrabFood

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.1.3

 Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from grabfood.models.currency import Currency
from grabfood.models.dine_in import DineIn
from grabfood.models.payment import Payment
from grabfood.models.pos_item import POSItem
from grabfood.models.pos_price_details import PosPriceDetails
from typing import Optional, Set
from typing_extensions import Self

class PosOrder(BaseModel):
    """
    The POSOrder indicates the detail order information from POS system.
    """ # noqa: E501
    order_id: Optional[StrictStr] = Field(default=None, description="The long orderID in grab system.", alias="orderID")
    partner_order_id: Optional[StrictStr] = Field(default=None, description="The orderID in pos system.", alias="partnerOrderID")
    merchant_id: Optional[StrictStr] = Field(default=None, description="The merchant's ID is the one in GrabFood's database.", alias="merchantID")
    partner_merchant_id: Optional[StrictStr] = Field(default=None, description="The merchant ID in pos system.", alias="partnerMerchantID")
    order_time: Optional[datetime] = Field(default=None, description="The UTC time that a consumer places the order, based on ISO_8601/RFC3339.", alias="orderTime")
    order_state: Optional[StrictStr] = Field(default=None, description="The order state in POS system, eg, COMPLETED.", alias="orderState")
    currency: Optional[Currency] = None
    items: Optional[List[POSItem]] = Field(default=None, description="The ordered items in an array of JSON Object. ")
    price: Optional[PosPriceDetails] = None
    dine_in: Optional[DineIn] = Field(default=None, alias="dineIn")
    payments: Optional[List[Payment]] = Field(default=None, description="An array of payment objects. `null` when there is no payment info from pos. This is only applicable for STO order")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["orderID", "partnerOrderID", "merchantID", "partnerMerchantID", "orderTime", "orderState", "currency", "items", "price", "dineIn", "payments"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PosOrder from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of currency
        if self.currency:
            _dict['currency'] = self.currency.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in items (list)
        _items = []
        if self.items:
            for _item_items in self.items:
                if _item_items:
                    _items.append(_item_items.to_dict())
            _dict['items'] = _items
        # override the default output from pydantic by calling `to_dict()` of price
        if self.price:
            _dict['price'] = self.price.to_dict()
        # override the default output from pydantic by calling `to_dict()` of dine_in
        if self.dine_in:
            _dict['dineIn'] = self.dine_in.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in payments (list)
        _items = []
        if self.payments:
            for _item_payments in self.payments:
                if _item_payments:
                    _items.append(_item_payments.to_dict())
            _dict['payments'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if dine_in (nullable) is None
        # and model_fields_set contains the field
        if self.dine_in is None and "dine_in" in self.model_fields_set:
            _dict['dineIn'] = None

        # set to None if payments (nullable) is None
        # and model_fields_set contains the field
        if self.payments is None and "payments" in self.model_fields_set:
            _dict['payments'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PosOrder from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "orderID": obj.get("orderID"),
            "partnerOrderID": obj.get("partnerOrderID"),
            "merchantID": obj.get("merchantID"),
            "partnerMerchantID": obj.get("partnerMerchantID"),
            "orderTime": obj.get("orderTime"),
            "orderState": obj.get("orderState"),
            "currency": Currency.from_dict(obj["currency"]) if obj.get("currency") is not None else None,
            "items": [POSItem.from_dict(_item) for _item in obj["items"]] if obj.get("items") is not None else None,
            "price": PosPriceDetails.from_dict(obj["price"]) if obj.get("price") is not None else None,
            "dineIn": DineIn.from_dict(obj["dineIn"]) if obj.get("dineIn") is not None else None,
            "payments": [Payment.from_dict(_item) for _item in obj["payments"]] if obj.get("payments") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


