# coding: utf-8

"""
Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

GrabFood

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.1.3

 Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from grabfood.models.redeem_result import RedeemResult
from grabfood.models.voucher import Voucher
from typing import Optional, Set
from typing_extensions import Self

class RedeemDineInVoucherResponse(BaseModel):
    """
    
    """ # noqa: E501
    certificate_id: Optional[StrictStr] = Field(default=None, description="This certificateID is decoded from scanning the QR code, and 1:1 mapping with `voucherCode`.", alias="certificateID")
    voucher_code: Optional[Annotated[str, Field(strict=True, max_length=11)]] = Field(default=None, description="A short code for the dine-in voucher purchased by the user.", alias="voucherCode")
    voucher: Optional[Voucher] = None
    redeem_result: Optional[RedeemResult] = Field(default=None, alias="redeemResult")
    merchant_id: Optional[StrictStr] = Field(default=None, description="The merchant's ID that is in GrabFood's database.", alias="merchantID")
    campaign_id: Optional[StrictStr] = Field(default=None, description="The dine-in voucher campaign's ID in GrabFood's database.", alias="campaignID")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["certificateID", "voucherCode", "voucher", "redeemResult", "merchantID", "campaignID"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RedeemDineInVoucherResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of voucher
        if self.voucher:
            _dict['voucher'] = self.voucher.to_dict()
        # override the default output from pydantic by calling `to_dict()` of redeem_result
        if self.redeem_result:
            _dict['redeemResult'] = self.redeem_result.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RedeemDineInVoucherResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "certificateID": obj.get("certificateID"),
            "voucherCode": obj.get("voucherCode"),
            "voucher": Voucher.from_dict(obj["voucher"]) if obj.get("voucher") is not None else None,
            "redeemResult": RedeemResult.from_dict(obj["redeemResult"]) if obj.get("redeemResult") is not None else None,
            "merchantID": obj.get("merchantID"),
            "campaignID": obj.get("campaignID")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


