# coding: utf-8

"""
Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

GrabFood

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.1.3

 Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class VirtualContact(BaseModel):
    """
    A JSON object containing the virtual contact information, where the validity period is 6 hours. Refer [FAQ](#section/Order/How-to-contact-customer-using-the-virtual-contact) on how the virtual contact works.
    """ # noqa: E501
    phone_number: Optional[Annotated[str, Field(strict=True, max_length=30)]] = Field(default=None, description="The generated virtual phone number that will forward calls to the customer's actual phone number. Will be omitted if the `status` is not `ACTIVE`.", alias="phoneNumber")
    pin: Optional[Annotated[str, Field(strict=True, max_length=10)]] = Field(default=None, description="A unique PIN required when forwarding calls to the customer for verification and security. Will be omitted if the `status` is not `ACTIVE`.", alias="PIN")
    expired_at: Optional[StrictStr] = Field(default=None, description="The expiry time of the virtual contact in UTC based on ISO_8601/RFC3339. Will be omitted if the `status` is not `ACTIVE`.", alias="expiredAt")
    status: Optional[StrictStr] = Field(default=None, description="Indicates the current status and validity of the virtual contact. * `ACTIVE` - The virtual contact is valid. * `EXPIRED` - The virtual contact has expired and is no longer valid. * `UNAVAILABLE` - An internal error occurred while generating or retrieving the virtual contact. ")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["phoneNumber", "PIN", "expiredAt", "status"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ACTIVE', 'EXPIRED', 'UNAVAILABLE']):
            raise ValueError("must be one of enum values ('ACTIVE', 'EXPIRED', 'UNAVAILABLE')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VirtualContact from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VirtualContact from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "phoneNumber": obj.get("phoneNumber"),
            "PIN": obj.get("PIN"),
            "expiredAt": obj.get("expiredAt"),
            "status": obj.get("status")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


