# coding: utf-8

"""
Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

GrabFood

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.1.3

 Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from grabfood.models.voucher_description_info import VoucherDescriptionInfo
from typing import Optional, Set
from typing_extensions import Self

class Voucher(BaseModel):
    """
    A JSON object containing dine-in voucher details.
    """ # noqa: E501
    title: Optional[StrictStr] = Field(default=None, description="The title of the voucher.")
    discounted_price: Optional[StrictStr] = Field(default=None, description="The amount paid after discount is applied in local currency.", alias="discountedPrice")
    original_price: Optional[StrictStr] = Field(default=None, description="The original amount before discount is applied in local currency.", alias="originalPrice")
    description_info: Optional[VoucherDescriptionInfo] = Field(default=None, alias="descriptionInfo")
    voucher_type: Optional[StrictStr] = Field(default=None, description="The type of the dine-in voucher.", alias="voucherType")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["title", "discountedPrice", "originalPrice", "descriptionInfo", "voucherType"]

    @field_validator('voucher_type')
    def voucher_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['CASH', 'ITEM']):
            raise ValueError("must be one of enum values ('CASH', 'ITEM')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Voucher from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of description_info
        if self.description_info:
            _dict['descriptionInfo'] = self.description_info.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Voucher from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "title": obj.get("title"),
            "discountedPrice": obj.get("discountedPrice"),
            "originalPrice": obj.get("originalPrice"),
            "descriptionInfo": VoucherDescriptionInfo.from_dict(obj["descriptionInfo"]) if obj.get("descriptionInfo") is not None else None,
            "voucherType": obj.get("voucherType")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


